### PR TITLE
Ported colorscheme to Dawn

### PR DESCRIPTION
**Pull request by CuboidRaptor**
Basically just replaced all Moon colors with Dawn colors as defined in the website palette, also slightly changed some things.
Screenshot

### CODE REVIEW

**Comment by ashbork** [comment]
Awesome, thank you!

**Comment by ashbork** [comment]
If you don't mind, could you also:
- Add yourself to the "Thank you" list
- Add some assets displaying your variant of the theme
I'd appreciate that a lot as I don't have a KDE machine spun up at the moment. Cheers!

**Comment by CuboidRaptor** [comment]
Ok, will do that when possible.
(also, there is no "Plasma Style" for Dawn as of yet. Should I just screenshot with the Moon style/theme?)

**Comment by ashbork** [comment]
Hm, that's true... Yeah, let's stick with that

**Pull request merged**
